version: '3'

volumes:
  pg_data_V:
  static_V:
  media_V:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_V:/var/lib/postgresql/data

  backend:
    image: neljuli07/foodgram_backend
    env_file: .env
    volumes:
      - static_V:/backend_static
      - media_V:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    image: neljuli07/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_V:/frontend_static

  gateway:
    image: neljuli07/foodgram_gateway
    volumes:
      - static_V:/staticfiles/
      - media_V:/app/media/    
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
